# Generated by Django 3.2.12 on 2022-04-16 06:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, null=True, verbose_name='Title')),
                ('start', models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='Start date')),
                ('end', models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='Start date')),
                ('event_id', models.CharField(default='N/A', max_length=1024, null=True, verbose_name='Event id')),
            ],
        ),
    ]
